version: '3'

services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
    - 8761:8761

  gateway-server:
    build: ./gateway-server
    container_name: gateway-server
    ports:
    - 8084:8084
    depends_on:
    - discovery-server
    links:
    - discovery-server

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
    - 8763:8763
    depends_on:
    - discovery-server
    links:
    - discovery-server

  phone-service-mysql:
    image: mysql:5.7
    container_name: phone-service-mysql
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=phones
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=secret
    ports:
    - 8083:8083

  phone-service:
    build: ./phone-service
    container_name: phone-service
    depends_on:
    - phone-service-mysql
    - discovery-server
    - config-server
    ports:
    - 8081:8081
    environment:
    - DATABASE_HOST=phone-service-mysql
    - DATABASE_USER=admin
    - DATABASE_PASSWORD=secret
    - DATABASE_NAME=phones
    - DATABASE_PORT=8083
    - DISCOVERY_SERVICE_HOST=discovery-server
    - DISCOVERY_SERVICE_PORT=8761
    links:
    - phone-service-mysql
    - discovery-server
    - config-server